---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageUpdateAutomation
metadata:
  name: porter-hello
  namespace: demo
spec:
  checkout:
    branch: main
    gitRepositoryRef:
      name: porter-hello
  commit:
    authorEmail: fluxcdbot@users.noreply.github.com
    authorName: fluxcdbot
    messageTemplate: '[ci skip] update porter-hello installations'
  interval: 10s

